
FROM osrf/ros:noetic-desktop-full
# ----------------------------------------------------------------------------
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Asia/Shanghai \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US:zh \
    LC_ALL=en_US.UTF-8

RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak
RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirrors.aliyun.com/ubuntu/|g' /etc/apt/sources.list
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# 打包工具以及Python依赖安装
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y bash-completion openssh-server net-tools nano zsh git curl x11-apps iputils-ping sshpass fakeroot debhelper unzip zip tree python3-pip

RUN pip3 install pytest pytest-dependency pytest-env bloom sh requests fire -i https://pypi.tuna.tsinghua.edu.cn/simple
# ----------------------------------------------------------------------------


# ----------------------------------------------------------------------------
# 创建组和用户并指定 UID/GID
ARG USERNAME=ros
ARG UID=1002
ARG GID=1002
RUN groupadd -g $GID ros && \
    useradd -m -u $UID -g $GID -s /bin/zsh ros && \
    echo "ros:1234" | chpasswd && \
    usermod -aG sudo ros
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# 安装zsh及oh-my-zsh和插件
USER ros
ENV HOME=/home/ros
RUN sh -c "$(wget -O- https://install.ohmyz.sh/)" --unattended
RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
RUN sed -i 's/^ZSH_THEME=".*"/ZSH_THEME="powerlevel10k\/powerlevel10k"/' ~/.zshrc 
RUN sed -i 's/^plugins=(.*)/plugins=(git zsh-syntax-highlighting zsh-autosuggestions)/' ~/.zshrc
# 修复p10k配置无法rainbow的问题
RUN echo "[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh" >> ~/.zshrc && \
    echo "export TERM=xterm-256color" >> ~/.zshrc && \
    echo "export TERM=xterm-256color" >> ~/.bashrc
COPY .p10k.zsh /home/ros/.p10k.zsh
# ----------------------------------------------------------------------------


# ----------------------------------------------------------------------------
# SSH 配置
USER root
RUN mkdir -p /etc/ssh /var/run/sshd
RUN ssh-keygen -A
RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
RUN echo 'Port 10022' >> /etc/ssh/sshd_config
# ----------------------------------------------------------------------------


# ----------------------------------------------------------------------------
# 配置ros环境变量
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN echo "source /opt/ros/noetic/setup.zsh" >> ~/.zshrc
RUN echo "umask 0002" >> ~/.bashrc
RUN echo "umask 0002" >> ~/.zshrc
# ----------------------------------------------------------------------------
ENV DISPLAY=:0

USER ros
WORKDIR /home/ros

EXPOSE 10022
# 启动 sshd 服务并保持容器不退出
CMD ["sshpass", "-p", "1234", "sudo", "/usr/sbin/sshd", "-D"]
# ----------------------------------------------------------------------------
