# 示例:
# actionlib:     # 功能包名称
#   ubuntu: ros-foxy-actionlib  # deb包名,需要注意的是 如果功能包名称中有下划线,在deb包中需要更改为-
# 该文件用来标识ros依赖,即如果在功能包中有依赖 自定义的功能包的话,需要在该文件中列出
rtipc_runtime:
  ubuntu: [zj-humanoid-rtipc-runtime]
uplimb_runtime:
  ubuntu: [zj-humanoid-uplimb-runtime]
pico_runtime:
  ubuntu: [zj-humanoid-ros-foxy-pico-runtime]
legged_common:
  ubuntu: [zj-humanoid-ros-foxy-legged-common]
legged_hw:
  ubuntu: [zj-humanoid-ros-foxy-legged-hw]
legged_messages:
  ubuntu: [zj-humanoid-ros-foxy-legged-messages]
legged_nav_description:
  ubuntu: [zj-humanoid-ros-foxy-legged-nav-description]
legged_nav2_hw:
  ubuntu: [zj-humanoid-ros-foxy-legged-nav2-hw]
legged_nav2_fsm:
  ubuntu: [zj-humanoid-ros-foxy-legged-nav2-fsm]
legged_rl_controllers:
  ubuntu: [zj-humanoid-ros-foxy-legged-rl-controllers]
legged_control:
  ubuntu: [zj-humanoid-ros-foxy-legged-control]
libbase_fsm:
  ubuntu: [zj-humanoid-ros-foxy-libbase-fsm]
libonnxruntime:
  ubuntu: [zj-humanoid-ros-foxy-libonnxruntime]
legged_nav3t_hw:
  ubuntu: [zj-humanoid-ros-foxy-legged-nav3t-hw]
upperlimb:
  ubuntu: [zj-humanoid-ros-foxy-upperlimb]
upperlimb_msgs:
  ubuntu: [zj-humanoid-ros-foxy-upperlimb-msgs]
uplimb_interface:
  ubuntu: [zj-humanoid-ros-foxy-uplimb-interface]
hand:
  ubuntu: [zj-humanoid-ros-foxy-hand]
hand_msgs:
  ubuntu: [zj-humanoid-ros-foxy-hand-msgs]
dexhand_interface:
  ubuntu: [zj-humanoid-ros-foxy-dexhand-interface]
zj_robot:
  ubuntu: [zj-humanoid-ros-foxy-zj-robot]
robot_state:
  ubuntu: [zj-humanoid-ros-foxy-robot-state]
audio:
  ubuntu: [zj-humanoid-ros-foxy-audio]

manipulation:
  ubuntu: [zj-humanoid-ros-foxy-manipulation]
navigation:
  ubuntu: [zj-humanoid-ros-foxy-navigation]
sensor:
  ubuntu: [zj-humanoid-ros-foxy-sensor]
chassis_msgs:
  ubuntu: [zj-humanoid-ros-foxy-chassis-msgs]
media_play:
  ubuntu: [zj-humanoid-ros-foxy-media-play]
pico_states:
  ubuntu: [zj-humanoid-ros-foxy-pico-states]
text_show:
  ubuntu: [zj-humanoid-ros-foxy-text-show]
livox_ros_driver2:
  ubuntu: [zj-humanoid-ros-foxy-livox-ros-driver2]

naviai_speaker:
  ubuntu: [zj-humanoid-ros-foxy-naviai-speaker]
naviai_mic_driver:
  ubuntu: [zj-humanoid-ros-foxy-naviai-mic-driver]
naviai_audio_launch:
  ubuntu: [zj-humanoid-ros-foxy-naviai-audio-launch]

logging:
  ubuntu: [zj-humanoid-logging]
bbox_collision_model:
  ubuntu: [zj-humanoid-ros-foxy-bbox-collision-model]
i2_s_description:
  ubuntu: [zj-humanoid-ros-foxy-i2-s-description]
jk1_description:
  ubuntu: [zj-humanoid-ros-foxy-jk1-description]
jk2_description:
  ubuntu: [zj-humanoid-ros-foxy-jk2-description]
u1_description:
  ubuntu: [zj-humanoid-ros-foxy-u1-description]
wa1_400l_description:
  ubuntu: [zj-humanoid-ros-foxy-wa1-400l-description]
wa1_d11_description:
  ubuntu: [zj-humanoid-ros-foxy-wa1-d11-description]
wa2_a2_lite_description:
  ubuntu: [zj-humanoid-ros-foxy-wa2-a2-lite-description]
wa2_l_ty20_description:
  ubuntu: [zj-humanoid-ros-foxy-wa2-l-ty20-description]
wa2_ls_description:
  ubuntu: [zj-humanoid-ros-foxy-wa2-ls-description]
zyd_description:
  ubuntu: [zj-humanoid-ros-foxy-zyd-description]