name: Docker Build CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ROS Humble on Jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ROS Humble on Jammy
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.HumbleOnJammy
          platforms: linux/amd64
          push: false
          tags: cros22-humble:latest
          build-args: |
            UID=1001
            GID=1001
          cache-from: type=gha,scope=Dockerfile.HumbleOnJammy
          cache-to: type=gha,mode=max,scope=Dockerfile.HumbleOnJammy
